langfuse:
  salt: "eDHOjeq8x+f1fh9oXNKf9Q12hFJI9gelI8W8CHQ1Ilk=" # Generate via `openssl rand -hex 32`
nextauth:
  secret: "your-nextauth-secret"
postgresql:
  enabled: true # Set to false if using external RDS
  auth:
    password: "postgreDBPWD"
clickhouse:
  enabled: true
  auth:
    password: "your-clickhouse-password"


