langfuse:
  salt: 
    secretKeyRef:
      name: langfuse-salt
      key: salt # Generate via `openssl rand -hex 32`

  # NextAuth configuration
  nextauth:
    # -- When deploying to production, set the `nextauth.url` value to the canonical URL of your site.
    url: http://localhost:3000
    # -- Used to encrypt the NextAuth.js JWT, and to hash email verification tokens. Can be configured by value or existing secret reference.
    secret:
      value: "d25e7696b67ed5869c041b47d8b9992ac6ede705a99934e82c41d549ff170866"
postgresql:
  enabled: true # Set to false if using external RDS
  auth:
    password: "postgreDBPWD"
clickhouse:
  enabled: true
  auth:
    password: "clickhousepassword"
  shards: 1
  replicas: 1


global:
  storageClass: gp2   # EKS example

zookeeper:
  replicaCount: 1
  resources: {}


s3:
  auth:
    rootPassword:
      value: "minio123"   # temporary for dev
  resources: {}




