annotations:
  category: Database
  images: "- name: kubectl\n  image: docker.io/bitnami/kubectl:1.32.2-debian-12-r0\n\
    - name: os-shell\n  image: docker.io/bitnami/os-shell:12-debian-12-r37\n- name:\
    \ redis-exporter\n  image: docker.io/bitnami/redis-exporter:1.67.0-debian-12-r7\n\
    - name: valkey\n  image: docker.io/bitnami/valkey:8.0.2-debian-12-r2\n- name:\
    \ valkey-sentinel\n  image: docker.io/bitnami/valkey-sentinel:8.0.2-debian-12-r2\n"
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.0.2
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Valkey is an open source (BSD) high-performance key/value datastore that
  supports a variety workloads such as caching, message queues, and can act as a primary
  database.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
keywords:
- valkey
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: valkey
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/valkey
version: 2.2.4
