annotations:
  category: Database
  images: "- name: os-shell\n  image: docker.io/bitnami/os-shell:12-debian-12-r37\n\
    - name: postgres-exporter\n  image: docker.io/bitnami/postgres-exporter:0.16.0-debian-12-r8\n\
    - name: postgresql\n  image: docker.io/bitnami/postgresql:17.3.0-debian-12-r1\n"
  licenses: Apache-2.0
apiVersion: v2
appVersion: 17.3.0
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: PostgreSQL (Postgres) is an open source object-relational database known
  for reliability and data integrity. ACID-compliant, it supports foreign keys, joins,
  views, triggers and stored procedures.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
- postgresql
- postgres
- database
- sql
- replication
- cluster
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: postgresql
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/postgresql
version: 16.4.9
