global:
  security:
    allowInsecureImages: false
  defaultStorageClass: gp2
  storageClass: gp2

nameOverride: ""
fullnameOverride: ""

langfuse:
  logging:
    level: info
    format: text

  # Langfuse SALT (required)
  salt:
    value: ""
    secretKeyRef:
      name: langfuse-app-secrets
      key: LANGFUSE_SALT

  # Optional license key
  licenseKey:
    value: 
    secretKeyRef:
      name: langfuse-app-secrets
      key: LANGFUSE_LICENSE_KEY

  # Encryption key (recommended)
  encryptionKey:
    value: ""
    secretKeyRef:
      name: langfuse-app-secrets
      key:  

  allowedOrganizationCreators: []

  features:
    telemetryEnabled: true
    signUpDisabled: false
    experimentalFeaturesEnabled: false

  nodeEnv: production

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  smtp:
    # If you use SMTP, put full URL in secret and reference via additionalEnv in web/worker if needed
    connectionUrl: ""
    fromAddress: ""

  ingress:
    enabled: true
    additionalLabels: {}
    annotations: {}
    className: ""
    hosts:
      - host: langfuse.aigfintinc.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      enabled: false
      secretName: ""

  podSecurityContext: {}
  securityContext: {}

  nodeSelector: {}
  tolerations: []
  affinity: {}
  dnsConfig: {}

  pod:
    annotations: {}
    labels: {}
    topologySpreadConstraints: []
  deployment:
    annotations: {}
    strategy: {}

  replicas: 1
  revisionHistoryLimit: 10
  resources: {}

  image:
    tag: null
    pullPolicy: Always
    pullSecrets: []

  additionalEnv: []
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraLifecycle: {}

  web:
    image:
      repository: langfuse/langfuse
      tag: null
      pullPolicy: null
      pullSecrets: null
    deployment:
      additionalLabels: {}
      annotations: {}
      strategy: {}
    pod:
      annotations: {}
      labels: {}
      topologySpreadConstraints: null
      extraContainers: []
      additionalEnv: []
    service:
      type: ClusterIP
      port: 3000
      externalPort: null
      nodePort: null
      additionalLabels: {}
      annotations: {}
    resources: {}
    replicas: null
    revisionHistoryLimit: null
    keda:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      pollingInterval: 30
      triggerType: cpu
      metricType: Utilization
      value: "50"
      containerName: ""
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
    vpa:
      enabled: false
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
    hostAliases: []
    livenessProbe:
      path: /api/public/health
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      path: /api/public/ready
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

  worker:
    image:
      repository: langfuse/langfuse-worker
      tag: null
      pullPolicy: null
      pullSecrets: null
    deployment:
      additionalLabels: {}
      annotations: {}
      strategy: {}
    pod:
      annotations: {}
      labels: {}
      topologySpreadConstraints: null
      extraContainers: []
      additionalEnv: []
    resources: {}
    replicas: null
    revisionHistoryLimit: null
    keda:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      pollingInterval: 30
      triggerType: cpu
      metricType: Utilization
      value: "50"
      containerName: ""
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
    vpa:
      enabled: false
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1

  nextauth:
    url: https://langfuse.aigfintinc.com
    secret:
      value: ""
      secretKeyRef:
        name: langfuse-app-secrets
        key: NEXTAUTH_SECRET

postgresql:
  deploy: true
  host: ""
  port: null
  args: ""
  directUrl: ""
  shadowDatabaseUrl: ""
  image:
    repository: bitnamilegacy/postgresql
    tag: 17.3.0-debian-12-r1
  auth:
    username: postgres
    # use existing secret, do NOT keep password in values
    password: ""
    existingSecret: langfuse-postgres-secret
    secretKeys:
      userPasswordKey: postgres-password
    database: postgres_langfuse
    args: ""

  migration:
    autoMigrate: true

  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432

redis:
  deploy: true
  host: ""
  port: 6379
  image:
    repository:  bitnamilegacy/valkey

  tls:
    enabled: false
    caPath: ""
    certPath: ""
    keyPath: ""

  auth:
    # IMPORTANT: keep username default unless you know youâ€™re using ACL users
    username: default
    password: ""
    existingSecret: langfuse-redis-secret
    existingSecretPasswordKey: valkey-password
    database: 0

  cluster:
    enabled: false
    nodes: []
  architecture: standalone

  primary:
    extraFlags:
      - --maxmemory-policy noeviction

clickhouse:
  deploy: true
  host: ""
  httpPort: 8123
  nativePort: 9000
  database: default
  image:  
    repository: bitnamilegacy/clickhouse

  zookeeper:
    image:
      repository: bitnamilegacy/zookeeper
    resourcesPreset: ""
    resources:
      requests:
        cpu: 250m
        memory: 256Mi

    

  auth:
    username: default
    password: ""
    existingSecret: langfuse-clickhouse-secret
    existingSecretKey: clickhouse-password

  migration:
    url: ""
    ssl: false
    autoMigrate: true

  # (you can tune these later; these are heavy by default)
  clusterEnabled: true
  shards: 1
  replicaCount: 3
  resourcesPreset: 2xlarge


s3:
  deploy: true
  storageProvider: s3
  image:
    repository: bitnamilegacy/minio
  resourcesPreset: ""
  resources:
    requests:
      cpu: 250m
      memory: 256Mi


  bucket: ""
  region: auto
  endpoint: ""
  forcePathStyle: true

  accessKeyId:
    value: ""
    secretKeyRef:
      name: langfuse-s3-secret
      key: S3_ACCESS_KEY_ID
  secretAccessKey:
    value: ""
    secretKeyRef:
      name: langfuse-s3-secret
      key: S3_SECRET_ACCESS_KEY




  gcs:
    credentials:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: GCS_CREDENTIALS_JSON

  concurrency:
    reads: 50
    writes: 50

  eventUpload:
    bucket: ""
    prefix: ""
    region: ""
    endpoint: ""
    forcePathStyle: null
    accessKeyId:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_ACCESS_KEY_ID
    secretAccessKey:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_SECRET_ACCESS_KEY

  batchExport:
    enabled: true
    bucket: ""
    prefix: ""
    region: ""
    endpoint: ""
    forcePathStyle: null
    accessKeyId:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_ACCESS_KEY_ID
    secretAccessKey:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_SECRET_ACCESS_KEY

  mediaUpload:
    enabled: true
    bucket: ""
    prefix: ""
    region: ""
    endpoint: ""
    forcePathStyle: null
    accessKeyId:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_ACCESS_KEY_ID
    secretAccessKey:
      value: ""
      secretKeyRef:
        name: langfuse-s3-secret
        key: S3_SECRET_ACCESS_KEY
    maxContentLength: 1000000000
    downloadUrlExpirySeconds: 3600

  defaultBuckets: langfuse

  auth:
    rootUser: minio
    rootPassword: ""
    existingSecret: langfuse-s3-minio-secret
    rootUserSecretKey: root-user
    rootPasswordSecretKey: root-password

extraManifests: []