global:
  security:
    allowInsecureImages: true
nameOverride: ''
fullnameOverride: ''
langfuse:
  logging:
    level: info
    format: text
  salt:
    value: ''
    secretKeyRef:
      name: ''
      key: ''
  licenseKey:
    value: ''
    secretKeyRef:
      name: ''
      key: ''
  allowedOrganizationCreators: []
  encryptionKey:
    value: ''
    secretKeyRef:
      name: ''
      key: ''
  features:
    telemetryEnabled: true
    signUpDisabled: false
    experimentalFeaturesEnabled: false
  nodeEnv: production
  serviceAccount:
    create: true
    annotations: {}
    name: ''
  smtp:
    connectionUrl: ''
    fromAddress: ''
  ingress:
    enabled: true
    additionalLabels: {}
    annotations: {}
    className: nginx
    hosts:
    - host: langfuse.aigfintinc.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
      enabled: false
      secretName: ''
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  dnsConfig: {}
  pod:
    annotations: {}
    labels: {}
    topologySpreadConstraints: []
  deployment:
    annotations: {}
    strategy: {}
  replicas: 1
  revisionHistoryLimit: 10
  resources: {}
  image:
    tag: null
    pullPolicy: Always
    pullSecrets: []
  additionalEnv: []
  extraContainers: []
  extraVolumes: []
  extraInitContainers: []
  extraVolumeMounts: []
  extraLifecycle: {}
  web:
    image:
      repository: langfuse/langfuse
      tag: null
      pullPolicy: null
      pullSecrets: null
    deployment:
      additionalLabels: {}
      annotations: {}
      strategy: {}
    pod:
      annotations: {}
      labels: {}
      topologySpreadConstraints: null
      extraContainers: []
      additionalEnv: []
    service:
      type: ClusterIP
      port: 3000
      externalPort: null
      nodePort: null
      additionalLabels: {}
      annotations: {}
    resources: {}
    replicas: null
    revisionHistoryLimit: null
    keda:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      pollingInterval: 30
      triggerType: cpu
      metricType: Utilization
      value: '50'
      containerName: ''
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
    vpa:
      enabled: false
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
    hostAliases: []
    livenessProbe:
      path: /api/public/health
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      path: /api/public/ready
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
  worker:
    image:
      repository: langfuse/langfuse-worker
      tag: null
      pullPolicy: null
      pullSecrets: null
    deployment:
      additionalLabels: {}
      annotations: {}
      strategy: {}
    pod:
      annotations: {}
      labels: {}
      topologySpreadConstraints: null
      extraContainers: []
      additionalEnv: []
    resources: {}
    replicas: null
    revisionHistoryLimit: null
    keda:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      pollingInterval: 30
      triggerType: cpu
      metricType: Utilization
      value: '50'
      containerName: ''
    hpa:
      enabled: false
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
    vpa:
      enabled: false
      controlledResources: []
      maxAllowed: {}
      minAllowed: {}
      updatePolicy:
        updateMode: Auto
    livenessProbe:
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
  nextauth:
    url: http://localhost:3000
    secret:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
postgresql:
  deploy: true
  host: ''
  port: null
  args: ''
  directUrl: ''
  shadowDatabaseUrl: ''
  image:
    repository: bitnamilegacy/postgresql
  auth:
    username: postgres
    password: ''
    existingSecret: ''
    secretKeys:
      userPasswordKey: password
    database: postgres_langfuse
    args: ''
  migration:
    autoMigrate: true
  architecture: standalone
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      storageClass: gp2
redis:
  deploy: true
  host: ''
  port: 6379
  image:
    repository: bitnamilegacy/valkey
  tls:
    enabled: false
    caPath: ''
    certPath: ''
    keyPath: ''
  auth:
    username: null
    password: ''
    existingSecret: ''
    existingSecretPasswordKey: ''
    database: 0
  cluster:
    enabled: false
    nodes: []
  architecture: standalone
  primary:
    extraFlags:
    - --maxmemory-policy noeviction
    persistence:
      enabled: false
clickhouse:
  deploy: true
  host: ''
  httpPort: 8123
  nativePort: 9000
  database: default
  image:
    repository: bitnamilegacy/clickhouse
  zookeeper:
    image:
      repository: bitnamilegacy/zookeeper
    resources:
      limits:
        cpu: null
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  auth:
    username: default
    password: ''
    existingSecret: ''
    existingSecretKey: ''
  migration:
    url: ''
    ssl: false
    autoMigrate: true
  clusterEnabled: false
  shards: 1
  replicaCount: 1
  resourcesPreset: small
  persistence:
    storageClass: gp2
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      memory: 4Gi
s3:
  deploy: true
  storageProvider: s3
  image:
    repository: bitnamilegacy/minio
  bucket: ''
  region: auto
  endpoint: ''
  forcePathStyle: true
  accessKeyId:
    value: ''
    secretKeyRef:
      name: ''
      key: ''
  secretAccessKey:
    value: ''
    secretKeyRef:
      name: ''
      key: ''
  gcs:
    credentials:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
  concurrency:
    reads: 50
    writes: 50
  eventUpload:
    bucket: ''
    prefix: ''
    region: ''
    endpoint: ''
    forcePathStyle: null
    accessKeyId:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
    secretAccessKey:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
  batchExport:
    enabled: true
    bucket: ''
    prefix: ''
    region: ''
    endpoint: ''
    forcePathStyle: null
    accessKeyId:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
    secretAccessKey:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
  mediaUpload:
    enabled: true
    bucket: ''
    prefix: ''
    region: ''
    endpoint: ''
    forcePathStyle: null
    accessKeyId:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
    secretAccessKey:
      value: ''
      secretKeyRef:
        name: ''
        key: ''
    maxContentLength: 1000000000
    downloadUrlExpirySeconds: 3600
  defaultBuckets: langfuse
  auth:
    rootUser: minio
    rootPassword: ''
    existingSecret: ''
    rootUserSecretKey: ''
    rootPasswordSecretKey: ''
  persistence:
    storageClass: gp2
extraManifests: []
