annotations:
  category: Infrastructure
  images: "- name: os-shell\n  image: docker.io/bitnami/os-shell:12-debian-12-r39\n\
    - name: zookeeper\n  image: docker.io/bitnami/zookeeper:3.9.3-debian-12-r8\n"
  licenses: Apache-2.0
apiVersion: v2
appVersion: 3.9.3
dependencies:
- name: common
  repository: file://charts/common
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache ZooKeeper provides a reliable, centralized register of configuration
  data and services for distributed applications.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/zookeeper/img/zookeeper-stack-220x234.png
keywords:
- zookeeper
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: zookeeper
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/zookeeper
version: 13.7.4
